apiVersion: v1
kind: Service
metadata:
  name: data-service
  namespace: {{ .Values.namespace }}
  labels:
    component: {{ template "elasticsearch.name" . }}
    {{- if .Values.elasticsearchConfig.breakoutRoles }}
    role: client
    {{- end }}
spec:
  ports:
  - name: tcp-9200
    protocol: TCP
    port: 9200 
    targetPort: 9200
  - name: tcp-9300
    protocol: TCP
    port: 9300
    targetPort: 9300
  selector:
    component: {{ template "elasticsearch.name" . }}
    {{- if .Values.elasticsearchConfig.breakoutRoles }}
    role: client
    {{- end }}
    
---
apiVersion: v1
kind: Service
metadata:
  name: es-discovery
  namespace: {{ .Values.namespace }}
  labels:
    component: {{ template "elasticsearch.name" . }}
    {{- if ne .Values.elasticsearchConfig.breakoutRoles }}
    role: master
    {{- end }}
spec:
  ports:
  - name: tcp-9300
    protocol: TCP
    port: 9300 
    targetPort: 9300
  clusterIP: None
  selector:
    component: {{ template "elasticsearch.name" . }}
    {{- if ne .Values.elasticsearchConfig.breakoutRoles }}
    role: master
    {{- end }}

{{- if .Values.elasticsearchConfig.breakoutRoles }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "elasticsearch.fullname" . }}-master-headless
  namespace: {{ .Values.namespace }}
  labels:
    component: {{ template "elasticsearch.name" . }}
    role: master
spec:
  clusterIP: None
  selector:
    component: {{ template "elasticsearch.name" . }}
    role: master
    
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "elasticsearch.fullname" . }}-client-headless
  namespace: {{ .Values.namespace }}
  labels:
    component: {{ template "elasticsearch.name" . }}
    role: client
spec:
  clusterIP: None
  selector:
    component: {{ template "elasticsearch.name" . }}
    role: client
    
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "elasticsearch.fullname" . }}-data-headless
  namespace: {{ .Values.namespace }}
  labels:
    component: {{ template "elasticsearch.name" . }}
    role: data
spec:
  clusterIP: None
  selector:
    component: {{ template "elasticsearch.name" . }}
    role: data
    
{{- else }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "elasticsearch.fullname" . }}-headless
  namespace: {{ .Values.namespace }}
  labels:
    component: {{ template "elasticsearch.name" . }}
spec:
  clusterIP: None
  selector:
    component: {{ template "elasticsearch.name" . }}
    
{{- end }}